//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace codeSvcTest.xmlSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="xmlSvc.IXmlWebService")]
    public interface IXmlWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXmlWebService/listLessonPlans", ReplyAction="http://tempuri.org/IXmlWebService/listLessonPlansResponse")]
        string[] listLessonPlans();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXmlWebService/getLessonPlan", ReplyAction="http://tempuri.org/IXmlWebService/getLessonPlanResponse")]
        System.Xml.Linq.XElement[] getLessonPlan(string xmlUrl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXmlWebServiceChannel : codeSvcTest.xmlSvc.IXmlWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XmlWebServiceClient : System.ServiceModel.ClientBase<codeSvcTest.xmlSvc.IXmlWebService>, codeSvcTest.xmlSvc.IXmlWebService {
        
        public XmlWebServiceClient() {
        }
        
        public XmlWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XmlWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] listLessonPlans() {
            return base.Channel.listLessonPlans();
        }
        
        public System.Xml.Linq.XElement[] getLessonPlan(string xmlUrl) {
            return base.Channel.getLessonPlan(xmlUrl);
        }
    }
}
